# Generated by Django 5.2.17 on 2026-08-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_rows', models.PositiveIntegerField()),
                ('accepted_count', models.PositiveIntegerField()),
                ('error_count', models.PositiveIntegerField()),
                ('root_count', models.PositiveIntegerField()),
                ('manager_count', models.PositiveIntegerField()),
                ('cycle_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanEmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('root', 'Root'), ('manager', 'Manager'), ('cycle', 'Cycle member')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('employee_id', models.TextField()),
                ('employee_name', models.TextField(blank=True)),
                ('email', models.TextField()),
                ('department', models.TextField(blank=True)),
                ('direct_report_count', models.PositiveIntegerField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to='imports.importscan')),
            ],
            options={
                'ordering': ['category', 'position'],
                'indexes': [models.Index(fields=['scan', 'category', 'position'], name='scan_category_position_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'category', 'position'), name='unique_scan_detail_position')],
            },
        ),
        migrations.CreateModel(
            name='ScanIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('source_row', models.PositiveIntegerField()),
                ('messages', models.JSONField(default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_issues', to='imports.importscan')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('scan', 'position'), name='unique_scan_issue_position')],
            },
        ),
    ]
