# Generated by Django 5.2.17 on 2026-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanissue',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='scanemployeedetail',
            index=models.Index(fields=['scan', 'category', 'employee_id'], name='scan_category_emp_id_idx'),
        ),
        migrations.AddIndex(
            model_name='scanemployeedetail',
            index=models.Index(fields=['scan', 'category', 'employee_name'], name='scan_category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='scanemployeedetail',
            index=models.Index(fields=['scan', 'category', 'email'], name='scan_category_email_idx'),
        ),
        migrations.AddIndex(
            model_name='scanemployeedetail',
            index=models.Index(fields=['scan', 'category', 'department'], name='scan_category_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='scanemployeedetail',
            index=models.Index(fields=['scan', 'category', 'direct_report_count'], name='scan_category_reports_idx'),
        ),
        migrations.AddIndex(
            model_name='scanissue',
            index=models.Index(fields=['scan', 'source_row'], name='scan_issue_source_idx'),
        ),
    ]
