# Generated by Django 5.2.17 on 2026-08-23 11:12

from django.db import migrations


def populate_search_text(apps, schema_editor):
    scan_issue = apps.get_model("imports", "ScanIssue")
    database = schema_editor.connection.alias
    last_primary_key = 0

    while True:
        batch = list(
            scan_issue.objects.using(database)
            .filter(pk__gt=last_primary_key)
            .order_by("pk")[:1000]
        )
        if not batch:
            break

        for issue in batch:
            messages = issue.messages if isinstance(issue.messages, list) else []
            issue.search_text = "\n".join(str(message) for message in messages)
        scan_issue.objects.using(database).bulk_update(
            batch,
            ["search_text"],
            batch_size=1000,
        )
        last_primary_key = batch[-1].pk


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_scanissue_search_text_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_search_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
